hostname="NanoPi-NEO"

wlans_rtwn0="wlan0"

ifconfig_wlan0="WPA DHCP"

hostapd="NO"

clear_log_enable="YES"
clear_tmp_enable="YES"

cron_enable="NO"
growfs_enable="YES"
ntpd_enable="NO"
sendmail_enable="NONE"
setpass_enable="NO"
sshd_enable="NO"
syslogd_enable="NO"

