autoboot_delay="0"
beastie_disable="YES"

boot_mute="YES"
boot_verbose="NO"

if_rtwn_usb="YES"
if_wlan_usb="YES"

rtwn_load="YES"

wlan_load="YES"
wlan_amrr_load="YES"
wlan_ccmp_load="YES"
wlan_tkip_load="YES"
wlan_wep_load="YES"

legal.realtek.license_ack="1"
