server:
	username: unbound
	directory: /usr/local/etc/unbound
	chroot: /usr/local/etc/unbound
	auto-trust-anchor-file: /usr/local/etc/unbound/root.key
	hide-identity: yes
	hide-version: yes
	interface: 10.0.0.1
	access-control: 10.0.0.0/24 allow
	local-zone: "setup.nanopi-neo.localhost" redirect
	local-data: "setup.nanopi-neo.localhost. IN A 10.0.0.1"
