interface=urtwn0
ctrl_interface=/var/run/hostapd
ctrl_interface_group=wheel
ssid=nanopi-neo
macaddr_acl=0
wpa=2
wpa_psk=071e96baa7696214712a3944bf3e9c03af2599528a438556db1d94ee5b991636
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
auth_algs=1
