if [ -r /etc/defaults/rc.conf ]; then
	. /etc/defaults/rc.conf
fi

rc_configured=YES

hostname=NanoPi-NEO

creds_msdos=YES
creds_msdos_partition=/boot

resize_disklabel=YES
resize_root=YES
resize_root_flags="-p"
resize_root_postcmd="/sbin/reboot -n"

dhcpd=NO
dhcpcd=YES
dhcpcd_flags="-q urtwn0 -b"

ntpd=YES
ntpd_flags="-g"

hostapd=NO
mdnsd=NO
postfix=NO
sshd=NO

wpa_supplicant=NO
wpa_supplicant_flags="-B -i urtwn0 -c /etc/wpa_supplicant.conf"
