PATH=$PATH:/usr/local/sbin:/usr/local/bin
export PATH

hostname="NanoPi-NEO"

wlans_rtwn0="wlan0"

# Enable WPA station/Host AP modes.
if [ -e /nanopi-neo/.setup ]
then
	create_args_wlan0="wlanmode hostap"

	ifconfig_wlan0="inet 10.0.0.1 netmask 255.255.255.0"

	FIRST_BOOT="YES"
else
	ifconfig_wlan0="WPA DHCP"

	FIRST_BOOT="NO"
fi

clear_log_enable="YES"
clear_tmp_enable="YES"

dhcpd_enable="$FIRST_BOOT"
dhcpd_ifaces="wlan0"

ntpd_enable="NO"
ntpd_sync_on_start="NO"

nanopi-neo_enable="YES"
cron_enable="NO"
growfs_enable="YES"
hostapd_enable="$FIRST_BOOT"
setpass_enable="NO"
setup_enable="$FIRST_BOOT"
sshd_enable="NO"
syslogd_enable="NO"
