hostname="NanoPi-NEO"

wlans_rtwn0="wlan0 wlan1"

# Enable station/Host AP modes.
if [ -e /nanopi-neo/.setup ]; then
	create_args_wlan1="wlanmode hostap"
else
	ifconfig_wlan0="WPA DHCP"
fi

clear_log_enable="YES"
clear_tmp_enable="YES"

ntpd_enable="NO"
ntpd_sync_on_start="NO"

cron_enable="NO"
growfs_enable="YES"
hostapd_enable="YES"
setpass_enable="NO"
sshd_enable="NO"
syslogd_enable="NO"
