WITHOUT_ACCT=yes
WITHOUT_ASSERT_DEBUG=yes
WITHOUT_BSDINSTALL=yes
WITHOUT_BLUETOOTH=yes
WITHOUT_CALENDAR=yes
WITHOUT_CDDL=yes
WITHOUT_CVS=yes
WITHOUT_DEBUG_FILES=yes
WITHOUT_DIALOG=yes
WITHOUT_DICT=yes
WITHOUT_EXAMPLES=yes
WITHOUT_FINGER=yes
WITHOUT_FLOPPY=yes
WITHOUT_FREEBSD_UPDATE=yes
WITHOUT_FTP=yes
WITHOUT_GAMES=yes
WITHOUT_GCC=yes
WITHOUT_GDB=yes
WITHOUT_HTML=yes
WITHOUT_ISCSI=yes
WITHOUT_JAIL=yes
WITHOUT_KERBEROS=yes
WITHOUT_KVM=yes
WITHOUT_LEGACY_CONSOLE=yes
WITHOUT_LLDB=yes
WITHOUT_LPR=yes
WITHOUT_MAIL=yes
WITHOUT_MAKE=yes
WITHOUT_MAN=yes
WITHOUT_MODULE_DRM=yes
WITHOUT_MODULE_DRM2=yes
WITHOUT_NETGRAPH=yes
WITHOUT_PC_SYSINSTALL=yes
WITHOUT_PORTSNAP=yes
WITHOUT_PPP=yes
WITHOUT_SENDMAIL=yes
WITHOUT_SHAREDOCS=yes
WITHOUT_BSNMP=yes
WITHOUT_RADIUS_SUPPORT=yes
WITHOUT_SVNLITE=yes
WITHOUT_TALK=yes
WITHOUT_TCP_WRAPPERS=yes
WITHOUT_TCSH=yes
WITHOUT_TELNET=yes
WITHOUT_TESTS=yes
WITHOUT_TESTS_SUPPORT=yes
WITHOUT_TFTP=yes
