#!/bin/sh
#
# $FreeBSD: setpass,v 1.0 2020/03/21 00:00:00 nuxy Exp $
#

# PROVIDE: setpass
# REQUIRE: tty
# BEFORE:  SERVERS

. /etc/rc.subr

name="setpass"
start_cmd="setpass_start"
stop_cmd=":"

setpass_start()
{
	insecure=`grep -c 'root:*:0:0::0:0:Charlie' /etc/master.passwd`

	if [ $insecure -eq 1 ]
	then
		echo `openssl rand -hex 12` | pw usermod root -h 0
	fi
}

load_rc_config $name
run_rc_command "$1"